### ISSUE TITLE
Gemini support?

### ISSUE THREAD

**Issue by A-ZXY** [blazzbyte/OpenInterpreterUI#11]
Do you have plans for supporting Gemini?

**Comment by blazzbyte** [comment]
sadly to use Gemini has to be through VertexAI which is a paid platform and requires to load a json credentials file to use the models, which requires more validation methods in order to avoid problems with the json file and the login of the app into google cloud, but surely when the openinterpreter library decides to implement aistudio.google.com also us, because there, we just need to put an api key

**Comment by blazzbyte** [comment]
@A-ZXY in the latest commit was added gemini support through VertexAI
