### ISSUE TITLE
How can csv input be handled?

### ISSUE THREAD

**Issue by s-nemoto** [blazzbyte/OpenInterpreterUI#12]
Is it possible to support analysis by importing csv?
I would like to put in a csv and have it parsed by a python program.

**Comment by IA-Programming** [comment]
that could it be done but, requires to handle a path directory in order to avoid clutter and a cleaning function that runs periodically to clean old csv files, but I would recommend you to use [LangChain: Chat with pandas DataFrame](https://chat-pandas-df.streamlit.app/) that will help you to save some tokens because does not think and run some extra code to get the output that you want

**Comment by IA-Programming** [comment]
also you can modify the system prompt in order to make it specialize in data analysis and you can put it directly into the prompt the read data from your csv, that's another way to see it

**Comment by blazzbyte** [comment]
@s-nemoto could you check if know work for your case, maybe using gpt-4, because know has the ability to display images create it by the model, let us know if it work for your use case to be able to close this issue
